### ISSUE TITLE
improvement request: list of failed tests

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.releng.buildtools#19]
One important task is to check for errors on https://download.eclipse.org/eclipse/downloads/drops4/I20221017-1800/testResults.php

But it requires to manually click into all bundles and manually search for the errors.
It would help if the main page would have a table with

`bundle | Class | Name | stacktrace`
for all failed test in all bundles.
bonus:
Add the number of fails per test in the last month and order by failCount desc
`bundle | Class | Name | stacktrace | failCount↓`

I would offer the work time but i don't know how to test it. I only see it could be done here:
https://github.com/eclipse-platform/eclipse.platform.releng.buildtools/blob/master/bundles/org.eclipse.build.tools/src/org/eclipse/releng/generators/TestResultsGenerator.java#L910

**Comment by akurtakov** [comment]
There are not many people versatile in this code. I will do my best to help you with this one but unfortunately I don't know much more than you.

**Comment by akurtakov** [comment]
I more and more realize we should not be creating and generating pages and etc. but rather delegate to the tools we use. E.g. there is https://ci.eclipse.org/releng/job/AutomatedTests/job/ep431I-unit-cen64-gtk3-java21/4/testReport/ . 
Having a link to the jenkins test results (or whatever other CI is used at some point) is the way to go IMO, the list of failed tests with times and etc. is shown conveniently at the top of the page. 
Do you agree with this path?

**Comment by iloveeclipse** [comment]
> Do you agree with this path?

*Additional* links are OK, but throwing away current overview would be major loss of functionality.
Note also, Jenkins pages are extremely slow, so links to them are useful but not solution.

**Comment by akurtakov** [comment]
I'll be extremely direct here - I don't see anyone willing to work on these pages generation and I can't dedicate time for that. So how I see things is we use current things with links to jenkins as long as they work, if they break - link to jenkins it is.
The question about agreeing with this path is exactly about this issue - having a list of failed tests from all bundles. If someone plans to add that - please say so, otherwise I'll close this as done when I have the link to jenkins result added.

**Comment by jukzi** [comment]
the idea o this ticket  was to 1) get overview over all failed test and 2) get an idea which is not a random fail. If any of this can be seen on jenkins i'll be happy.

**Comment by akurtakov** [comment]
I have to put some more context here: 
* Today java was removed by webmaster from download.eclipse.org
* This broke an I-build during opening stream work
* It costed me good chunk of time to figure what is going on and how/if we can not execute full blown eclipse on download.eclipse.org
* support for doing this is planned to be removed
* this feature relies on that 

One can see what happens in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/JenkinsJobs/Releng/collectResults.groovy
So the days for this feature in its current form are numbered and we have to find a way forward that is achievable with current amount of time spent.

**Comment by akurtakov** [comment]
> the idea o this ticket was to 1) get overview over all failed test and 2) get an idea which is not a random fail. If any of this can be seen on jenkins i'll be happy.

1) is half there - you can get an overview per os/ws/arch combo . See https://ci.eclipse.org/releng/job/AutomatedTests/job/ep431I-unit-cen64-gtk3-java17/lastCompletedBuild/testReport/

**Comment by jukzi** [comment]
> 1. https://ci.eclipse.org/releng/job/AutomatedTests/job/ep431I-unit-cen64-gtk3-java17/4/testReport/

AAAAAAAAAAAAAAA so SLOOOW

**Comment by jukzi** [comment]
> 1. https://ci.eclipse.org/releng/job/AutomatedTests/job/ep431I-unit-cen64-gtk3-java17/4/testReport/

that accuracy ...
![image](https://github.com/eclipse-platform/eclipse.platform.releng.buildtools/assets/51790620/5a9ad1a3-8497-4246-84f3-ccfaa3b26440)

**Comment by jukzi** [comment]
> > the idea o this ticket was to 1) get overview over all failed test and 2) get an idea which is not a random fail. If any of this can be seen on jenkins i'll be happy.
> 
> 1. is half there - you can get an overview per os/ws/arch combo . See https://ci.eclipse.org/releng/job/AutomatedTests/job/ep431I-unit-cen64-gtk3-java17/4/testReport/

and parsing errors
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep431I-unit-cen64-gtk3-java17/lastCompletedBuild/testReport/[line%20103_%20OK%20pattern=*a*b*g*n*t,%20text=abcd_abcdefg_abcdefghijk_abcdefghijklmnop/txt]/testStringMatchCaseInsensitive_line_103__OK_pattern__a_b_g_n_t__text_abcd_abcdefg_abcdefghijk_abcdefghijklmnop_txt_/

hard to fall in love with that

**Comment by iloveeclipse** [comment]
> that accuracy ...

I assume they hit integer overflow. No one writes so many tests, so obviously no one saw this error so far.

**Comment by jukzi** [comment]
> No one writes so many tests

or combined OSes with different line-endings?:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.buildtools/assets/51790620/c8cd8742-63be-431a-b803-c5d0078e6b6a)

**Comment by jukzi** [comment]
> 2) get an idea which is not a random fail.

something positive: that can be seen in the age column:
![image](https://github.com/eclipse-platform/eclipse.platform.releng.buildtools/assets/51790620/c1c7cfbf-12e1-4b89-86c9-088b92c97a6c)

**Comment by jukzi** [comment]
> * It costed me good chunk of time to figure what is going on and how/if we can not execute full blown eclipse on download.eclipse.org

@akurtakov thanks for doing it, that unnoticed work so important.

**Comment by jukzi** [comment]
closing, as not planned, since in principle jenkins shows "age" of a failed test. just sad how slow our jenkins instances are
