### ISSUE TITLE
convert app failing

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.buildtools#39]
Look at e.g. https://download.eclipse.org/eclipse/downloads/drops4/I20230802-1800/buildlogs/mb300_gatherEclipseParts.sh.log . It's full with 
```
[eclipse.convert] org.xml.sax.SAXParseException; systemId: file:///home/jenkins/agent/workspace/Builds/I-build-4.29/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20230802-1800/compilelogs/plugins/org.eclipse.pde.build.tests_1.4.100.v20230728-0611/@dot.xml; lineNumber: 3; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
```

**Comment by jukzi** [comment]
i will.

**Comment by jukzi** [comment]
a stacktrace would help, can you give one or explain how to locally reproduce?

**Comment by akurtakov** [comment]
On a second thought having an eclipse app to parst xml and produce html is an overkill. If you look at https://download.eclipse.org/eclipse/downloads/drops4/R-4.28-202306050440/compilelogs/plugins/org.eclipse.e4.tools.emf.ui_4.8.0.v20230510-1239/@dot.html it's generated by https://download.eclipse.org/eclipse/downloads/drops4/R-4.28-202306050440/compilelogs/plugins/org.eclipse.e4.tools.emf.ui_4.8.0.v20230510-1239/@dot.xml .
Doing the operation by xslt will simplify everything so much .
For local testing you should be able to use org.eclipse.releng.build.tools.convert.ant.Converter.main and give it the @dot.xml file to parse.

**Comment by akurtakov** [comment]
Even changing the build to use xslt (if/when available) should be easy as https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.tychoeclipsebuilder/eclipse/buildScripts/eclipse_convert.xml can be changed to call https://ant.apache.org/manual/Tasks/style.html.

**Comment by akurtakov** [comment]
So looking at output (https://download.eclipse.org/eclipse/downloads/drops4/I20230803-1800/buildlogs/mb300_gatherEclipseParts.sh.log) there is a new place failing with same error -
```
[indexResults] ERROR: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
[indexResults] java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
[indexResults] java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
[indexResults] org.eclipse.releng.generators.TestResultsGenerator.parseCompileLog(TestResultsGenerator.java:646)
[indexResults] org.eclipse.releng.generators.TestResultsGenerator.processCompileLogsDirectory(TestResultsGenerator.java:1018)
[indexResults] org.eclipse.releng.generators.TestResultsGenerator.processCompileLogsDirectory(TestResultsGenerator.java:1025)
[indexResults] org.eclipse.releng.generators.TestResultsGenerator.processCompileLogsDirectory(TestResultsGenerator.java:1025)
[indexResults] org.eclipse.releng.generators.TestResultsGenerator.parseCompileLogs(TestResultsGenerator.java:724)
[indexResults] org.eclipse.releng.generators.TestResultsGenerator.execute(TestResultsGenerator.java:398)
```

**Comment by akurtakov** [comment]
I've triggered new build https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/87/ to check whether this is good now.

**Comment by akurtakov** [comment]
warnings shown properly https://download.eclipse.org/eclipse/downloads/drops4/I20230804-0220/compilelogs/plugins/org.eclipse.e4.tools.emf.ui_4.8.100.v20230727-0604/@dot.html
